prefixes: ['.', '!', '/']
language: ru
backends:
  - kind: vk
    token: <token-for-vk-here>
  - kind: tg
    token: <token-for-tg-here>
storages:
  - name: default
    kind: sqlite
    path: kutana.sqlite3
